/* steamprofiler.org - the owner panel's strings.

   Loaded after dict.js and merged into it. They live here rather than in the
   site's dictionary because the panel is not part of the public site: every
   visitor downloads dict.js, and eighty strings about triaging an inbox and
   the port this thing listens on are eighty strings nobody outside this
   machine has any business reading. */

const ADM_DICT = {
  en: {
    'adm.tab_census': 'count',
    'adm.cen_bar': 'what this is',
    'adm.cen_exp': 'experimental',
    'adm.cen_exp_why': 'Switched on to see whether it is any use. If it gets in the way of the people using the site, it comes back off - that is what the marking means, not that the numbers are to be distrusted and kept anyway.',
    'adm.cen_exp_soft': 'They are soft all the same, and in a way worth knowing: addresses get recycled, so one shared carrier address makes many people look like one, and the same person on wifi, on a phone and behind a VPN looks like several. A kind is a guess from behaviour and it gets it wrong. Read these as recurring visits, not as people.',
    'adm.cen_who': 'visits that came back',
    'adm.cen_who_note': 'Recognisable for seven days, then the secret is replaced and these become counts with no handle in them. Nothing here says which profile any of them asked for - there is no column for it.',
    'adm.cen_classes': 'by kind',
    'adm.cen_origins': 'by origin',
    'adm.cen_what': 'profiles looked up',
    'adm.cen_what_note': 'Counted per day, with no visitor attached. This half and the one above share no column, so they cannot be joined - not by me either.',
    'adm.cen_per_day': 'lookups per day',
    'adm.cen_history': 'earlier windows',
    'adm.cen_history_note': 'What survived a rotation: how many there were, of what kind, from where. The identifiers were deleted when the window turned, so there is nothing in here a person is in.',
    'adm.cen_none': 'Nothing counted yet.',
    'adm.cen_ephemeral': 'No CENSUS_SEED is set, so the seed is ephemeral and recurrence resets on every restart. Set one in .env.',
    'adm.cen_seen': 'seen',
    'adm.cen_returning': 'came back',
    'adm.cen_hits': 'requests',
    'adm.cen_live': 'in memory',
    'cen.class.visitor': 'person, probably',
    'cen.class.ai': 'AI crawler',
    'cen.class.search': 'search engine',
    'cen.class.tool': 'script or tool',
    'cen.class.scanner': 'scanner',
    'cen.class.unknown': 'cannot tell',
    'cen.conf.declared': 'declared',
    'cen.conf.likely': 'likely',
    'cen.conf.unsure': 'unsure',
    'err.no_admin_token': 'The owner\'s area is not configured (ADMIN_TOKEN is missing).',
    'err.bad_token': 'Invalid token.',
    'adm.confirm_delete': 'Delete message #{id} for good?',
    'adm.contact': 'contact:',
    'adm.delete': 'Delete',
    'adm.empty': 'Nothing here yet.',
    'adm.enter': 'Sign in',
    'adm.eyebrow': 'owner\'s area',
    'adm.from': 'came from {path}',
    'adm.gate_note': 'This panel runs in its own container and is not published by the public listener. It only answers configured addresses, and the api token stays in the server process rather than in this browser.',
    'adm.change_bar': 'first sign in',
    'adm.change_h1': 'Choose your password',
    'adm.change_note': 'Twelve characters or more. Every other open session ends when you save.',
    'adm.current': 'the password you were given',
    'adm.new': 'new password',
    'adm.password': 'password',
    'adm.save_pass': 'Save and continue',
    'adm.user': 'user',
    'adm.h1': 'Inbox',
    'adm.new': '{n} new',
    'adm.new_one': '1 new',
    'adm.nothing_new': 'nothing new',
    'adm.reply_ph': 'public reply (shows on the board)',
    'adm.save': 'Save',
    'adm.saved_private': 'saved - still private',
    'adm.saved_public': 'saved - it is on the public board',
    'adm.sign_in': 'sign in',
    'adm.title': 'Inbox - steamprofiler.org',
    'adm.total': 'total',
    'adm.vote_one': '1 vote',
    'adm.votes': '{n} votes',
    'adm.tab_blog': 'blog',
    'adm.blog_new': 'new post',
    'adm.blog_editing': 'editing',
    'adm.blog_unsaved': 'not saved',
    'adm.blog_none': 'No posts yet.',
    'adm.blog_slug': 'fixed address',
    'adm.blog_slug_ph': 'optional, the old kind',
    'adm.slug_lang': 'address in this language',
    'adm.slug_lang_ph': 'left empty, the post answers by its id alone',
    'adm.slug_ai': 'Write the addresses',
    'adm.slug_ai_none': 'Write a title first - the address is made out of it.',
    'adm.slug_ai_working': 'asking the machine at home...',
    'adm.slug_ai_done': 'done in {seconds}s with {model}. {n} written, read them before you save.',
    'adm.slug_ai_failed': '{langs} came back empty: those answer by the id until you try again.',
    'adm.blog_status': 'status',
    'adm.blog_origin': 'written in',
    'adm.blog_tags': 'tags',
    'adm.blog_tags_ph': 'comma separated, six at most',
    'adm.blog_title': 'title',
    'adm.blog_lede': 'lede',
    'adm.blog_optional': '- optional',
    'adm.blog_body': 'text',
    'adm.blog_save': 'save',
    'adm.blog_clear': 'new post',
    'adm.blog_open': 'open \u2197',
    'adm.blog_edit': 'edit',
    'adm.blog_saved_live': 'saved, and live',
    'adm.blog_saved_draft': 'saved as a draft',
    'adm.blog_confirm_delete': 'Delete /blog/{slug}? Every vote on it goes with it.',
    'adm.blog_help': 'Markers: <code>## heading</code>, <code>- list</code>, <code>&gt; quote</code>, <code>**bold**</code>, <code>*italic*</code>, <code>`code`</code>, <code>[text](/link)</code>, and <code>```</code> around a block of code. A blank line starts a paragraph; a single line break inside one does not. Anything else is printed as it was typed.',
    'adm.tr_do': 'Translate from the original',
    'adm.tr_flag': 'machine translation, warn the reader',
    'adm.tr_same': 'This is the original. Pick another language, or change the origin above.',
    'adm.tr_empty': 'Write the {lang} version first - that is what gets translated.',
    'adm.tr_overwrite': 'Replace what is written in {lang} with a fresh translation?',
    'adm.tr_working': 'translating on the machine at home, a few minutes...',
    'adm.tr_done': 'done in {seconds}s with {model}. Read it before you save.',
    'adm.tab_mail': 'Feedback',
    'adm.tab_block': 'Blocks',
    'adm.blocks_none': 'No address is shut out, and none has written.',
    'adm.block_open': 'shut out',
    'adm.block_over': 'expired',
    'adm.block_gone': 'no ban on record',
    'adm.block_appeals': '{n} written',
    'adm.block_since': 'first seen {when}',
    'adm.block_until': 'opens {when}',
    'adm.block_lifts': 'let back in {n}x before',
    'adm.block_silent': 'This address has not written anything.',
    'adm.block_locked': 'No appeal from this address, so there is nothing to let out. It stays shut out until the ban runs out on its own.',
    'adm.block_quiet': '{n} shut out and silent. Nothing written, nothing to answer, nothing to lift.',
    'adm.block_show': 'Show them anyway',
    'adm.block_hide': 'Fold them away',
    'adm.block_open_n': 'shut out',
    'adm.block_repeat_n': 'repeat',
    'adm.block_waiting': 'waiting on you',
    'adm.paths_more': '+{n} more',
    'adm.mark_read': 'Mark read',
    'adm.bans': 'Shut out right now',
    'adm.bans_none': 'Nobody is shut out.',
    'adm.unban': 'Let back in',
    'adm.unbanned': 'Let back in. The gate opened at once.',
    'adm.confirm_unban': 'Let this address back in? It is recorded, so if it earns another ban you will be told.',
    'adm.repeat': 'REPEAT · let in {n}x before',
    'adm.ban_hits': '{n} paths tried',
    'adm.ban_until': 'until {when}',
  },
  pt: {
    'adm.tab_census': 'contagem',
    'adm.cen_bar': 'o que isso é',
    'adm.cen_exp': 'experimental',
    'adm.cen_exp_why': 'Ligado pra ver se serve. Se atrapalhar quem usa o site, é desligado - é isso que a marcação quer dizer, e não que os números são pra desconfiar e ficar do mesmo jeito.',
    'adm.cen_exp_soft': 'Ainda assim eles são moles, e de um jeito que vale saber: endereços são reciclados, então um endereço compartilhado de operadora faz muita gente parecer uma só, e a mesma pessoa no wifi, no celular e atrás de uma VPN parece várias. O tipo é um chute pelo comportamento, e ele erra. Leia isso como visitas recorrentes, não como pessoas.',
    'adm.cen_who': 'visitas que voltaram',
    'adm.cen_who_note': 'Reconhecíveis por sete dias; depois o segredo é trocado e isso vira contagem sem alça nenhuma dentro. Nada aqui diz qual perfil qualquer uma delas consultou - não existe coluna pra isso.',
    'adm.cen_classes': 'por tipo',
    'adm.cen_origins': 'por origem',
    'adm.cen_what': 'perfis consultados',
    'adm.cen_what_note': 'Contados por dia, sem nenhum visitante amarrado. Esta metade e a de cima não têm nenhuma coluna em comum, então não dá pra cruzar - nem por mim.',
    'adm.cen_per_day': 'consultas por dia',
    'adm.cen_history': 'janelas anteriores',
    'adm.cen_history_note': 'O que sobreviveu a uma rotação: quantos eram, de que tipo, de onde. Os identificadores foram apagados quando a janela virou, então não tem nada aqui em que caiba uma pessoa.',
    'adm.cen_none': 'Nada contado ainda.',
    'adm.cen_ephemeral': 'Sem CENSUS_SEED, então a semente é efêmera e a recorrência recomeça a cada restart. Defina uma no .env.',
    'adm.cen_seen': 'vistas',
    'adm.cen_returning': 'voltaram',
    'adm.cen_hits': 'requisições',
    'adm.cen_live': 'na memória',
    'cen.class.visitor': 'pessoa, provável',
    'cen.class.ai': 'rastreador de IA',
    'cen.class.search': 'buscador',
    'cen.class.tool': 'script ou ferramenta',
    'cen.class.scanner': 'scanner',
    'cen.class.unknown': 'não dá pra dizer',
    'cen.conf.declared': 'declarado',
    'cen.conf.likely': 'provável',
    'cen.conf.unsure': 'indeterminado',
    'err.no_admin_token': 'A área do dono não está configurada (falta ADMIN_TOKEN).',
    'err.bad_token': 'Token inválido.',
    'adm.confirm_delete': 'Apagar o recado #{id} de vez?',
    'adm.contact': 'contato:',
    'adm.delete': 'Apagar',
    'adm.empty': 'Nada aqui ainda.',
    'adm.enter': 'Entrar',
    'adm.eyebrow': 'área do dono',
    'adm.from': 'veio de {path}',
    'adm.gate_note': 'Este painel roda em container próprio e não é publicado pelo listener público. Ele só responde aos endereços configurados, e o token da api fica no processo do servidor, não neste navegador.',
    'adm.change_bar': 'primeiro acesso',
    'adm.change_h1': 'Escolha sua senha',
    'adm.change_note': 'Doze caracteres ou mais. Toda outra sessão aberta cai quando você salvar.',
    'adm.current': 'a senha que te passaram',
    'adm.new': 'senha nova',
    'adm.password': 'senha',
    'adm.save_pass': 'Salvar e continuar',
    'adm.user': 'usuário',
    'adm.h1': 'Caixa de recados',
    'adm.new': '{n} novos',
    'adm.new_one': '1 novo',
    'adm.nothing_new': 'nada novo',
    'adm.reply_ph': 'resposta pública (aparece no quadro)',
    'adm.save': 'Salvar',
    'adm.saved_private': 'salvo - segue privado',
    'adm.saved_public': 'salvo - está no quadro público',
    'adm.sign_in': 'entrar',
    'adm.title': 'Caixa de recados - steamprofiler.org',
    'adm.total': 'total',
    'adm.vote_one': '1 voto',
    'adm.votes': '{n} votos',
    'adm.tab_blog': 'blog',
    'adm.blog_new': 'post novo',
    'adm.blog_editing': 'editando',
    'adm.blog_unsaved': 'não salvo',
    'adm.blog_none': 'Nenhum post ainda.',
    'adm.blog_slug': 'endereço fixo',
    'adm.blog_slug_ph': 'opcional, do tipo antigo',
    'adm.slug_lang': 'endereço nesta língua',
    'adm.slug_lang_ph': 'vazio, o post responde só pelo id',
    'adm.slug_ai': 'Escrever os endereços',
    'adm.slug_ai_none': 'Escreva um título antes - o endereço sai dele.',
    'adm.slug_ai_working': 'perguntando pra máquina de casa...',
    'adm.slug_ai_done': 'pronto em {seconds}s com {model}. {n} escritos, leia antes de salvar.',
    'adm.slug_ai_failed': '{langs} voltou vazio: responde pelo id até você tentar de novo.',
    'adm.blog_status': 'estado',
    'adm.blog_origin': 'escrito em',
    'adm.blog_tags': 'tags',
    'adm.blog_tags_ph': 'separadas por vírgula, no máximo seis',
    'adm.blog_title': 'título',
    'adm.blog_lede': 'chamada',
    'adm.blog_optional': '- opcional',
    'adm.blog_body': 'texto',
    'adm.blog_save': 'salvar',
    'adm.blog_clear': 'post novo',
    'adm.blog_open': 'abrir \u2197',
    'adm.blog_edit': 'editar',
    'adm.blog_saved_live': 'salvo, e no ar',
    'adm.blog_saved_draft': 'salvo como rascunho',
    'adm.blog_confirm_delete': 'Apagar /blog/{slug}? Os votos vão junto.',
    'adm.blog_help': 'Marcadores: <code>## título</code>, <code>- lista</code>, <code>&gt; citação</code>, <code>**negrito**</code>, <code>*itálico*</code>, <code>`código`</code>, <code>[texto](/link)</code>, e <code>```</code> em volta de um bloco de código. Linha em branco começa parágrafo; quebra de linha sozinha, não. O resto sai como foi digitado.',
    'adm.tr_do': 'Traduzir do original',
    'adm.tr_flag': 'tradução de máquina, avisar quem lê',
    'adm.tr_same': 'Este é o original. Escolha outra língua, ou mude a origem acima.',
    'adm.tr_empty': 'Escreva a versão em {lang} primeiro - é ela que vai ser traduzida.',
    'adm.tr_overwrite': 'Trocar o que está escrito em {lang} por uma tradução nova?',
    'adm.tr_working': 'traduzindo na máquina de casa, alguns minutos...',
    'adm.tr_done': 'pronto em {seconds}s com {model}. Leia antes de salvar.',
    'adm.tab_mail': 'Recados',
    'adm.tab_block': 'Bloqueios',
    'adm.blocks_none': 'Nenhum endereço bloqueado, e nenhum escreveu.',
    'adm.block_open': 'bloqueado',
    'adm.block_over': 'venceu',
    'adm.block_gone': 'sem ban registrado',
    'adm.block_appeals': '{n} escreveu',
    'adm.block_since': 'visto em {when}',
    'adm.block_until': 'abre {when}',
    'adm.block_lifts': 'já liberado {n}x',
    'adm.block_silent': 'Este endereço não escreveu nada.',
    'adm.block_locked': 'Sem apelação deste endereço, então não há o que liberar. Fica bloqueado até o ban vencer sozinho.',
    'adm.block_quiet': '{n} bloqueados e calados. Não escreveram nada, não há o que responder nem o que liberar.',
    'adm.block_show': 'Mostrar mesmo assim',
    'adm.block_hide': 'Dobrar de volta',
    'adm.block_open_n': 'bloqueados',
    'adm.block_repeat_n': 'reincidentes',
    'adm.block_waiting': 'esperando você',
    'adm.paths_more': '+{n} outros',
    'adm.mark_read': 'Marcar lido',
    'adm.bans': 'Bloqueados agora',
    'adm.bans_none': 'Ninguém bloqueado.',
    'adm.unban': 'Liberar',
    'adm.unbanned': 'Liberado. O portão abriu na hora.',
    'adm.confirm_unban': 'Liberar este endereço? Fica registrado, então se ele for banido de novo você é avisado.',
    'adm.repeat': 'REINCIDENTE · já liberado {n}x',
    'adm.ban_hits': '{n} caminhos tentados',
    'adm.ban_until': 'até {when}',
  },
  ru: {
    'adm.tab_census': 'подсчёт',
    'adm.cen_bar': 'что это такое',
    'adm.cen_exp': 'эксперимент',
    'adm.cen_exp_why': 'Включено, чтобы посмотреть, есть ли польза. Если это мешает тем, кто пользуется сайтом, его выключают - вот что означает пометка, а не то, что числам не стоит доверять, но они всё равно останутся.',
    'adm.cen_exp_soft': 'И всё же они мягкие, и стоит знать, в чём именно: адреса переиспользуются, поэтому один общий адрес оператора делает так, что много людей выглядят как один, а один и тот же человек по wi-fi, с телефона и через VPN выглядит как несколько. Тип - это догадка по поведению, и она ошибается. Читайте это как повторные визиты, а не как людей.',
    'adm.cen_who': 'визиты, которые вернулись',
    'adm.cen_who_note': 'Узнаваемы семь дней, затем секрет заменяется, и это становится числами без всякой ручки внутри. Ничто здесь не говорит, какой профиль кто-то из них смотрел, - для этого нет столбца.',
    'adm.cen_classes': 'по типу',
    'adm.cen_origins': 'по происхождению',
    'adm.cen_what': 'просмотренные профили',
    'adm.cen_what_note': 'Считаются по дням, без привязки к посетителю. У этой половины и у той, что выше, нет ни одного общего столбца, поэтому их нельзя соединить - и мне тоже.',
    'adm.cen_per_day': 'просмотров в день',
    'adm.cen_history': 'прежние окна',
    'adm.cen_history_note': 'То, что пережило смену окна: сколько их было, какого типа, откуда. Идентификаторы удалены при повороте окна, так что здесь нет ничего, во что уместился бы человек.',
    'adm.cen_none': 'Пока ничего не подсчитано.',
    'adm.cen_ephemeral': 'CENSUS_SEED не задан, поэтому семя временное и повторность сбрасывается при каждом перезапуске. Задайте его в .env.',
    'adm.cen_seen': 'замечено',
    'adm.cen_returning': 'вернулось',
    'adm.cen_hits': 'запросов',
    'adm.cen_live': 'в памяти',
    'cen.class.visitor': 'вероятно, человек',
    'cen.class.ai': 'ИИ-краулер',
    'cen.class.search': 'поисковик',
    'cen.class.tool': 'скрипт или утилита',
    'cen.class.scanner': 'сканер',
    'cen.class.unknown': 'не определить',
    'cen.conf.declared': 'заявлено',
    'cen.conf.likely': 'вероятно',
    'cen.conf.unsure': 'неясно',
    'err.no_admin_token': 'Зона владельца не настроена (нет ADMIN_TOKEN).',
    'err.bad_token': 'Неверный токен.',
    'adm.confirm_delete': 'Удалить сообщение #{id} навсегда?',
    'adm.contact': 'контакт:',
    'adm.delete': 'Удалить',
    'adm.empty': 'Пока пусто.',
    'adm.enter': 'Войти',
    'adm.eyebrow': 'зона владельца',
    'adm.from': 'пришло с {path}',
    'adm.gate_note': 'Эта панель работает в отдельном контейнере и не публикуется через публичный listener. Она отвечает только заданным адресам, а токен api остаётся в процессе сервера, а не в этом браузере.',
    'adm.change_bar': 'первый вход',
    'adm.change_h1': 'Выберите пароль',
    'adm.change_note': 'Двенадцать символов или больше. Все другие открытые сессии завершатся при сохранении.',
    'adm.current': 'выданный вам пароль',
    'adm.new': 'новый пароль',
    'adm.password': 'пароль',
    'adm.save_pass': 'Сохранить и продолжить',
    'adm.user': 'пользователь',
    'adm.h1': 'Входящие',
    'adm.new': '{n} новых',
    'adm.new_one': '1 новое',
    'adm.nothing_new': 'ничего нового',
    'adm.reply_ph': 'открытый ответ (видно на доске)',
    'adm.save': 'Сохранить',
    'adm.saved_private': 'сохранено - остаётся закрытым',
    'adm.saved_public': 'сохранено - на открытой доске',
    'adm.sign_in': 'вход',
    'adm.title': 'Входящие - steamprofiler.org',
    'adm.total': 'всего',
    'adm.vote_one': '1 голос',
    'adm.votes': '{n} голосов',
    'adm.tab_blog': 'блог',
    'adm.blog_new': 'новая запись',
    'adm.blog_editing': 'правка',
    'adm.blog_unsaved': 'не сохранено',
    'adm.blog_none': 'Записей пока нет.',
    'adm.blog_slug': 'постоянный адрес',
    'adm.blog_slug_ph': 'необязательно, старого вида',
    'adm.slug_lang': 'адрес на этом языке',
    'adm.slug_lang_ph': 'пусто - запись отвечает по одному id',
    'adm.slug_ai': 'Написать адреса',
    'adm.slug_ai_none': 'Сначала заголовок - адрес делается из него.',
    'adm.slug_ai_working': 'спрашиваю домашнюю машину...',
    'adm.slug_ai_done': 'готово за {seconds}с, модель {model}. Написано: {n}. Прочитайте перед сохранением.',
    'adm.slug_ai_failed': '{langs} вернулось пустым: отвечает по id, пока не попробуете снова.',
    'adm.blog_status': 'состояние',
    'adm.blog_origin': 'написано на',
    'adm.blog_tags': 'теги',
    'adm.blog_tags_ph': 'через запятую, не больше шести',
    'adm.blog_title': 'заголовок',
    'adm.blog_lede': 'вступление',
    'adm.blog_optional': '- необязательно',
    'adm.blog_body': 'текст',
    'adm.blog_save': 'сохранить',
    'adm.blog_clear': 'новая запись',
    'adm.blog_open': 'открыть \u2197',
    'adm.blog_edit': 'править',
    'adm.blog_saved_live': 'сохранено и опубликовано',
    'adm.blog_saved_draft': 'сохранено как черновик',
    'adm.blog_confirm_delete': 'Удалить /blog/{slug}? Голоса уйдут вместе с ней.',
    'adm.blog_help': 'Разметка: <code>## заголовок</code>, <code>- список</code>, <code>&gt; цитата</code>, <code>**жирный**</code>, <code>*курсив*</code>, <code>`код`</code>, <code>[текст](/ссылка)</code> и <code>```</code> вокруг блока кода. Пустая строка начинает абзац, одиночный перенос - нет. Всё остальное печатается как набрано.',
    'adm.tr_do': 'Перевести с оригинала',
    'adm.tr_flag': 'машинный перевод, предупредить читателя',
    'adm.tr_same': 'Это оригинал. Выберите другой язык или смените источник выше.',
    'adm.tr_empty': 'Сначала напишите версию на {lang} - именно её переводят.',
    'adm.tr_overwrite': 'Заменить написанное на {lang} новым переводом?',
    'adm.tr_working': 'перевод идёт на домашней машине, несколько минут...',
    'adm.tr_done': 'готово за {seconds}с, модель {model}. Прочитайте перед сохранением.',
    'adm.tab_mail': 'Сообщения',
    'adm.tab_block': 'Блокировки',
    'adm.blocks_none': 'Ни один адрес не заблокирован, и никто не писал.',
    'adm.block_open': 'заблокирован',
    'adm.block_over': 'истёк',
    'adm.block_gone': 'бана не записано',
    'adm.block_appeals': 'сообщений: {n}',
    'adm.block_since': 'впервые {when}',
    'adm.block_until': 'откроется {when}',
    'adm.block_lifts': 'ранее разблокирован {n} раз',
    'adm.block_silent': 'С этого адреса ничего не писали.',
    'adm.block_locked': 'Апелляции с этого адреса нет, снимать нечего. Останется заблокированным, пока бан не истечёт сам.',
    'adm.block_quiet': '{n} заблокированы и молчат. Ничего не написали, отвечать не на что и снимать нечего.',
    'adm.block_show': 'Всё равно показать',
    'adm.block_hide': 'Свернуть обратно',
    'adm.block_open_n': 'заблокировано',
    'adm.block_repeat_n': 'повторных',
    'adm.block_waiting': 'ждут вас',
    'adm.paths_more': 'ещё {n}',
    'adm.mark_read': 'Прочитано',
    'adm.bans': 'Сейчас заблокированы',
    'adm.bans_none': 'Никто не заблокирован.',
    'adm.unban': 'Разблокировать',
    'adm.unbanned': 'Разблокирован. Доступ открылся сразу.',
    'adm.confirm_unban': 'Разблокировать этот адрес? Это записывается, и если он снова получит бан, вам сообщат.',
    'adm.repeat': 'ПОВТОР · разблокирован {n} раз',
    'adm.ban_hits': 'путей опробовано: {n}',
    'adm.ban_until': 'до {when}',
  },
};

/* The panel's own keys join the shared ones, so t() finds both without knowing
   there are two sources. */
/* The dictionary is one language deep now - the panel loads dict.en.js - so the
   panel's own strings merge in flat, from the language that arrived. */
Object.assign(DICT, ADM_DICT[typeof DICT_LANG === 'string' ? DICT_LANG : 'en'] || ADM_DICT.en);
